// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/css/normalize.css"
    | "/fonts/JetBrains_Mono/JetBrainsMono-Italic-VariableFont_wght.ttf"
    | "/fonts/JetBrains_Mono/JetBrainsMono-VariableFont_wght.ttf"
    | "/fonts/JetBrains_Mono/OFL.txt"
    | "/fonts/JetBrains_Mono/README.txt"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-Bold.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-BoldItalic.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-ExtraBold.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-ExtraBoldItalic.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-ExtraLight.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-ExtraLightItalic.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-Italic.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-Light.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-LightItalic.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-Medium.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-MediumItalic.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-Regular.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-SemiBold.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-SemiBoldItalic.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-Thin.ttf"
    | "/fonts/JetBrains_Mono/static/JetBrainsMono-ThinItalic.ttf"
    | "/fonts/Press_Start_2P/OFL.txt"
    | "/fonts/Press_Start_2P/PressStart2P-Regular.ttf"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/96.png"
    | "/popup.html"
    | "/wxt.svg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
