import {
  SelectionContextType,
  SelectionDataType,
} from "$/modules/selection/models/selection";
import {
  PiArrowsCounterClockwise,
  PiPlant,
  PiLightbulb,
  PiFlask,
  PiPencilSimpleLine,
  PiFeather,
  PiPlusCircle,
  PiIdentificationBadge,
  PiChatCircleDots,
  PiTextAlignLeft,
  PiLightning,
  PiKey,
  PiMagnifyingGlass,
  PiListBullets,
  PiShoppingCartSimple,
  PiFireSimple,
  PiTranslate,
  PiCode,
  PiBug,
  PiArrowClockwise,
  PiChatCenteredText,
  PiWarningCircle,
  PiTrophy,
  PiListPlus,
  PiTable,
  PiQuestion,
  PiMusicNoteSimple,
  PiSuitcaseSimple,
  PiBookOpenText,
} from "react-icons/pi";
import { PageCategory } from "../../context/models/context";
import { PARAMETER_PRESETS } from "../../inference/models/inference_model";
import type { ActionDefinition } from "../models/action_models";

const ALL_PAGE_CATEGORIES = Object.values(PageCategory);
const ANY_CONTEXT = Object.values(SelectionContextType);
const ANY_DATA = Object.values(SelectionDataType);

export const PREDEFINED_ACTIONS: ActionDefinition[] = [
  {
    id: "define",
    name: "Define",
    description: "Provide a dictionary definition",
    pageCategories: ALL_PAGE_CATEGORIES,
    contextTypes: ANY_CONTEXT,
    dataTypes: [SelectionDataType.WORD, SelectionDataType.TEXT],
    systemPrompt:
      "You are a dictionary assistant. Provide a clear, concise definition for the given word or phrase. Include the part of speech and, if applicable, example sentences. \n\n**IMPORTANT:** Format the output using extensive Markdown. Use headings (`## Definition`, `## Examples`), bold (`**word**`), italics (`*part of speech*`), and bullet points (`*`) for examples.",
    userPrompt: "Define the term or phrase: {{selection}}",
    llmParams: PARAMETER_PRESETS.FACTUAL,
    icon: PiBookOpenText,
  },
  {
    id: "synonyms",
    name: "Synonyms",
    description: "List words with similar meanings",
    pageCategories: ALL_PAGE_CATEGORIES,
    contextTypes: ANY_CONTEXT,
    dataTypes: [SelectionDataType.WORD, SelectionDataType.TEXT],
    systemPrompt:
      "You are a thesaurus assistant. Provide a list of synonyms for the given word or phrase. Organize synonyms by different shades of meaning where applicable, and include brief notes about subtle differences in connotation or usage. \n\n**IMPORTANT:** Structure your output using extensive Markdown. Use headings (`## Meaning 1`), bullet points (`* synonym - *note*`), bold (`**word**`), and italics (`*nuance*`).",
    userPrompt: "List synonyms for: {{selection}}",
    llmParams: PARAMETER_PRESETS.BALANCED,
    icon: PiArrowsCounterClockwise,
  },
  {
    id: "etymology",
    name: "Etymology",
    description: "Explore the historical origin of a word",
    contextTypes: ANY_CONTEXT,
    dataTypes: [SelectionDataType.WORD, SelectionDataType.TEXT],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are an etymology expert. Explain the origin and historical development of the given word. Trace it back to its roots if possible. \n\n**IMPORTANT:** Present the information using clear Markdown. Use headings (`## Origin`, `## History`), bold (`**language**`), italics (`*root word*`), and potentially bullet points (`*`).",
    userPrompt: "Explain the etymology of: {{selection}}",
    llmParams: PARAMETER_PRESETS.FACTUAL,
    icon: PiPlant,
  },
  {
    id: "explain_selection",
    name: "Explain",
    description: "Provide context or clarification",
    contextTypes: [
      SelectionContextType.GENERAL,
      SelectionContextType.QUOTE,
      SelectionContextType.MATH,
      SelectionContextType.DEFINITION_LIST,
      SelectionContextType.HEADER,
    ],
    dataTypes: [
      SelectionDataType.TEXT,
      SelectionDataType.SENTENCE,
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LATEX,
      SelectionDataType.TERMINAL_LIKE,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are an explanatory assistant. Provide a clear explanation, context, or background information for the selected text. Tailor the explanation to the likely context (e.g., explain jargon, define a concept, clarify a historical reference). If the text is technical (code, science), explain it simply first, then add detail. \n\n**IMPORTANT:** Use extensive Markdown formatting. Employ headings (`## Explanation`), bullet points (`*`), bold (`**term**`), italics (`*emphasis*`), code formatting (`code`), and blockquotes (`>`) for structure and readability.",
    userPrompt: "Explain the following:\n\n{{selection}}",
    llmParams: PARAMETER_PRESETS.BALANCED,
    icon: PiLightbulb,
  },
  {
    id: "breakdown",
    name: "Breakdown",
    description: "Explain jargon in simple terms",
    contextTypes: [
      SelectionContextType.GENERAL,
      SelectionContextType.CODE_BLOCK,
    ],
    dataTypes: [
      SelectionDataType.TEXT,
      SelectionDataType.SENTENCE,
      SelectionDataType.CODE_LIKE,
    ],
    pageCategories: [
      PageCategory.DEV_DOCS,
      PageCategory.SCIENTIFIC,
      PageCategory.CODE_REPO,
      PageCategory.DOCUMENTATION,
      PageCategory.HEALTH,
      PageCategory.FINANCE,
      PageCategory.LAW,
      PageCategory.WIKI,
      PageCategory.TEXTBOOKS,
      PageCategory.JOURNALS,
    ],
    systemPrompt:
      "You are a technical concept explainer. Take the selected technical term or concept (potentially from development, science, medicine, finance, law, etc.) and explain it in simple, accessible language. Start with a general explanation a non-expert could understand, then provide more technical detail if appropriate. Include real-world examples or analogies where helpful. \n\n**IMPORTANT:** Format the explanation using Markdown. Use headings (`## Explanation`), bullet points (`*`), and bold (`**key term**`).",
    userPrompt: "Explain this technical term: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    icon: PiFlask,
  },
  {
    id: "grammar",
    name: "Grammar",
    description: "Fix grammar and spelling issues",
    contextTypes: [SelectionContextType.INPUT],
    dataTypes: [
      SelectionDataType.TEXT,
      SelectionDataType.SENTENCE,
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.MARKDOWN,
      SelectionDataType.EMAIL,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a grammar assistant. Analyze the provided text for grammatical errors, spelling mistakes, and awkward phrasing. Suggest corrections. \n\n**IMPORTANT:** Present the corrections clearly using Markdown. Use blockquotes (`>`) for the original text, list errors with bullet points (`* **Error:** description`), and provide suggestions (`* **Suggestion:** corrected text`). Use bold/italics for emphasis.",
    userPrompt: "Check the grammar of this text: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    icon: PiPencilSimpleLine,
  },
  {
    id: "spellcheck",
    name: "Spellcheck",
    description: "Fix spelling issues",
    contextTypes: [SelectionContextType.INPUT],
    dataTypes: [SelectionDataType.WORD],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a spellcheck assistant. Analyze the provided text for spelling mistakes. Suggest corrections. \n\n**IMPORTANT:** Present the corrections clearly using Markdown. Use blockquotes (`>`) for the original text, list errors with bullet points (`* **Error:** description`), and provide suggestions (`* **Suggestion:** corrected text`). Use bold/italics for emphasis.",
    userPrompt: "Check the spelling of this text: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    icon: PiPencilSimpleLine,
  },
  {
    id: "rephrase",
    name: "Rephrase",
    description: "Rewrite in a different way",
    contextTypes: [SelectionContextType.INPUT],
    dataTypes: [
      SelectionDataType.TEXT,
      SelectionDataType.SENTENCE,
      SelectionDataType.PARAGRAPH,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a rephrasing assistant. Rewrite the provided text in several different ways (provide 2-3 options), maintaining its original meaning but varying sentence structure or vocabulary. \n\n**IMPORTANT:** Format the rewritten text clearly using Markdown. Use headings (`## Option 1`, `## Option 2`) and blockquotes (`>`) for each option.",
    userPrompt: "Rephrase this text: {{selection}}",
    llmParams: PARAMETER_PRESETS.BALANCED,
    icon: PiArrowsCounterClockwise,
  },
  {
    id: "simplify",
    name: "Simplify",
    description: "Make complex text easier to understand",
    contextTypes: [
      SelectionContextType.GENERAL,
      SelectionContextType.DEFINITION_LIST,
      SelectionContextType.QUOTE,
    ],
    dataTypes: [
      SelectionDataType.TEXT,
      SelectionDataType.SENTENCE,
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.MARKDOWN,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a simplification assistant. Rewrite the provided text using simpler language, shorter sentences, and more straightforward explanations. Aim for a reading level appropriate for a general audience (e.g., grade 8-10) unless the context suggests otherwise (e.g., medical text for laypersons). Preserve all important information and meaning. If the text is medical or highly technical, explicitly state you are simplifying the language, not providing advice. \n\n**IMPORTANT:** Present the simplified text using Markdown. Use headings (`## Simplified Version`), bullet points for key ideas if helpful, and bold (`**key term**`).",
    userPrompt: "Simplify this text: {{selection}}",
    llmParams: PARAMETER_PRESETS.BALANCED,
    icon: PiFeather,
  },
  {
    id: "expand",
    name: "Expand",
    description: "Elaborate with more details or examples",
    contextTypes: [
      SelectionContextType.GENERAL,
      SelectionContextType.LIST,
      SelectionContextType.HEADER,
      SelectionContextType.DEFINITION_LIST,
    ],
    dataTypes: [
      SelectionDataType.TEXT,
      SelectionDataType.SENTENCE,
      SelectionDataType.PARAGRAPH,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a content expansion specialist. Take the provided text and expand it with relevant details, examples, or explanations. Maintain the original meaning and tone while making the content more comprehensive. \n\n**IMPORTANT:** Format the expanded text using extensive Markdown. Use headings (`## Expanded Text`), bullet points (`*`), and bold (`**key term**`).",
    userPrompt: "Expand on this text: {{selection}}",
    llmParams: PARAMETER_PRESETS.CREATIVE,
    icon: PiPlusCircle,
  },
  {
    id: "formal",
    name: "Formalize",
    description: "Rewrite in a more formal tone",
    contextTypes: [SelectionContextType.INPUT],
    dataTypes: [
      SelectionDataType.TEXT,
      SelectionDataType.SENTENCE,
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.EMAIL,
      SelectionDataType.SOCIAL_MEDIA,
      SelectionDataType.MARKDOWN,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a formal tone assistant. Rewrite the provided text in a more formal tone, suitable for professional or academic contexts. Avoid slang, contractions, and overly casual phrasing. \n\n**IMPORTANT:** Present the rewritten text using Markdown. Use a heading (`## Formal Version`) and blockquotes (`>`).",
    userPrompt: "Convert this text to a formal tone: {{selection}}",
    llmParams: PARAMETER_PRESETS.BALANCED,
    icon: PiIdentificationBadge,
  },
  {
    id: "casual",
    name: "Casual",
    description: "Rewrite in a more conversational tone",
    contextTypes: [SelectionContextType.INPUT],
    dataTypes: [
      SelectionDataType.TEXT,
      SelectionDataType.SENTENCE,
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.EMAIL,
      SelectionDataType.MARKDOWN,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a conversational tone assistant. Rewrite the provided text in a more casual, friendly tone, suitable for social media or informal communication. Use contractions and simpler language where appropriate. \n\n**IMPORTANT:** Format the rewritten text using Markdown. Use a heading (`## Casual Version`) and blockquotes (`>`).",
    userPrompt: "Convert this text to a casual tone: {{selection}}",
    llmParams: PARAMETER_PRESETS.BALANCED,
    icon: PiChatCircleDots,
  },
  {
    id: "summarize",
    name: "Summarize",
    description: "Create a concise summary",
    contextTypes: [
      SelectionContextType.GENERAL,
      SelectionContextType.LIST,
      SelectionContextType.TABLE,
    ],
    dataTypes: [
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.MARKDOWN,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a summarization assistant. Create a concise summary of the provided text, capturing the main points and key information. Adapt the summary style based on context (e.g., neutral for news, technical for academic). \n\n**IMPORTANT:** Format the summary using clear Markdown. Use bullet points (`*`) for key points if helpful, or present as a well-structured paragraph. Use bold (`**key term**`).",
    userPrompt: "Summarize this text: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    highlight: true,
    icon: PiTextAlignLeft,
  },
  {
    id: "tldr",
    name: "TL;DR",
    description: "Ultra-concise summary (1-2 sentences)",
    contextTypes: [SelectionContextType.GENERAL, SelectionContextType.LIST],
    dataTypes: [
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.MARKDOWN,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a brevity expert. Create an extremely concise summary (TL;DR) of the provided text in 1-2 sentences. Focus only on the most essential takeaway. \n\n**IMPORTANT:** Format the summary using Markdown. Use a heading (`## TL;DR`) and bold (`**key term**`).",
    userPrompt: "Create a TL;DR for this text: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    icon: PiLightning,
  },
  {
    id: "key_points",
    name: "Key points",
    description: "Identify and list main points/arguments",
    contextTypes: [
      SelectionContextType.GENERAL,
      SelectionContextType.LIST,
      SelectionContextType.TABLE,
    ],
    dataTypes: [
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.MARKDOWN,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are an analysis assistant. Extract and list the key points, arguments, or insights from the provided text. Organize them in a clear, structured format. \n\n**IMPORTANT:** Present the key points using Markdown. Use a numbered list (`1.`) or bullet points (`*`). Use bold (`**topic**`).",
    userPrompt: "Extract the key points from this text: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    highlight: true,
    icon: PiKey,
  },
  {
    id: "extract_metadata",
    name: "Metadata",
    description: "Pull out specific details (names, dates, actions)",
    contextTypes: [
      SelectionContextType.GENERAL,
      SelectionContextType.LIST,
      SelectionContextType.TABLE,
      SelectionContextType.CODE_BLOCK,
    ],
    dataTypes: [
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.EMAIL,
      SelectionDataType.MARKDOWN,
      SelectionDataType.TERMINAL_LIKE,
      SelectionDataType.SOCIAL_MEDIA,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are an information extraction specialist. Analyze the provided text and extract key entities or information like names, organizations, locations, dates, monetary values, email addresses, phone numbers, or explicitly stated action items/tasks/requirements. If the context is email or meeting notes, focus on action items. If it's documentation, focus on requirements. \n\n**IMPORTANT:** Present the extracted information clearly using Markdown lists, categorized by type (e.g., `## People`, `## Action Items`).",
    userPrompt: "Extract key information from this text: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    icon: PiMagnifyingGlass,
  },
  {
    id: "outline",
    name: "Outline",
    description: "Generate a structured outline",
    contextTypes: [
      SelectionContextType.GENERAL,
      SelectionContextType.HEADER,
      SelectionContextType.LIST,
    ],
    dataTypes: [
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.MARKDOWN,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a structure specialist. Create a hierarchical outline from the provided text, capturing its organization, main points, and supporting details. \n\n**IMPORTANT:** Use extensive Markdown formatting. Employ nested bullet points (`*`, `  *`) or numbered lists (`1.`, `  a.`) to show hierarchy. Use bold (`**Section Title**`).",
    userPrompt: "Create an outline for this text: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    icon: PiListBullets,
  },

  {
    id: "brainstorm",
    name: "Brainstorm",
    description: "Generate related ideas or topics",
    contextTypes: [
      SelectionContextType.GENERAL,
      SelectionContextType.HEADER,
      SelectionContextType.QUOTE,
      SelectionContextType.DEFINITION_LIST,
      SelectionContextType.LIST,
    ],
    dataTypes: [
      SelectionDataType.WORD,
      SelectionDataType.TEXT,
      SelectionDataType.SENTENCE,
      SelectionDataType.PARAGRAPH,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a brainstorming assistant. Based on the selected text (a topic, question, or statement), generate a list of related ideas, concepts, potential follow-up points, alternative angles, or questions to explore further. Aim for diverse and creative suggestions. \n\n**IMPORTANT:** Present the ideas using a Markdown bulleted list (`*`).",
    userPrompt: "Brainstorm ideas related to: {{selection}}",
    llmParams: PARAMETER_PRESETS.CREATIVE,
    icon: PiLightbulb,
  },
  {
    id: "product_analyze",
    name: "Review",
    description: "Analyze product features/details",
    contextTypes: [
      SelectionContextType.GENERAL,
      SelectionContextType.LIST,
      SelectionContextType.TABLE,
    ],
    dataTypes: [
      SelectionDataType.TEXT,
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.MARKDOWN,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: [PageCategory.ECOMMERCE],
    systemPrompt:
      "You are a product analysis assistant. Analyze the product description, feature list, or specification table to identify key features, specifications, potential pros and cons, and comparable alternatives if possible from the text. Organize information clearly. Note if important information seems missing. \n\n**IMPORTANT:** Present the analysis using Markdown. Use headings (`## Features`, `## Pros/Cons`) and bullet points (`*`).",
    userPrompt: "Analyze this product description: {{selection}}",
    llmParams: PARAMETER_PRESETS.BALANCED,
    icon: PiShoppingCartSimple,
  },
  {
    id: "roast",
    name: "Roast",
    description: "Humorously critique (light-hearted)",
    contextTypes: [
      SelectionContextType.GENERAL,
      SelectionContextType.QUOTE,
      SelectionContextType.CODE_BLOCK,
    ],
    dataTypes: [
      SelectionDataType.TEXT,
      SelectionDataType.SENTENCE,
      SelectionDataType.PARAGRAPH,
      SelectionDataType.SOCIAL_MEDIA,
      SelectionDataType.CODE_LIKE,
      SelectionDataType.POETRY,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: [
      PageCategory.SOCIAL,
      PageCategory.FORUM,
      PageCategory.BLOG,
      PageCategory.GAMING,
      PageCategory.COMICS,
      PageCategory.GENERAL,
    ],
    systemPrompt:
      "You are a comedy roast assistant. Create a light-hearted, humorous critique of the selected text. Keep it playful, not mean. Focus on style, structure, or content quirks. Use wit, irony, and gentle sarcasm. \n\n**IMPORTANT:** Format the roast using Markdown. Use a heading (`## Roast`) and blockquotes (`>`).",
    userPrompt: "Humorously roast this: {{selection}}",
    llmParams: PARAMETER_PRESETS.CREATIVE,
    icon: PiFireSimple,
  },
  {
    id: "translate",
    name: "Translate",
    description: "Translate text (default: English)",
    contextTypes: ANY_CONTEXT,
    dataTypes: ANY_DATA,
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a translation assistant. Translate the provided text into the target language (default to English if unspecified by user prompt). Preserve the original meaning and tone as much as possible. If translating structured text (like a list), maintain the structure. \n\n**IMPORTANT:** Present the translation clearly using Markdown. Use a blockquote (`>`) for the original and provide the translation below. Use Markdown lists (`*`, `1.`) if needed.",
    userPrompt: "Translate the following text to English:\n\n{{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    icon: PiTranslate,
  },
  {
    id: "explain_code",
    name: "Explain",
    description: "Explain what the code does",
    contextTypes: [SelectionContextType.CODE_BLOCK],
    dataTypes: [SelectionDataType.CODE_LIKE, SelectionDataType.TERMINAL_LIKE],
    pageCategories: [
      PageCategory.DEV_DOCS,
      PageCategory.CODE_REPO,
      PageCategory.BLOG,
      PageCategory.FORUM,
      PageCategory.DOCUMENTATION,
      PageCategory.WIKI,
      PageCategory.PRODUCTIVITY,
      PageCategory.EDUCATION,
      PageCategory.TEXTBOOKS,
    ],
    systemPrompt:
      "You are a coding tutor. Explain the provided code snippet step-by-step. Identify the language if possible. Break down complex parts, explain the purpose of functions/variables, and note key patterns or potential issues. \n\n**IMPORTANT:** Use extensive Markdown. Use headings (`## Explanation`), bullet points (`*`), inline code (`variable`), and code blocks (```language\ncode\n```).",
    userPrompt: "Explain this code: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    highlight: true,
    icon: PiCode,
  },
  {
    id: "debug_code",
    name: "Debug",
    description: "Find potential bugs & improvements",
    contextTypes: [
      SelectionContextType.CODE_BLOCK,
      SelectionContextType.GENERAL,
    ],
    dataTypes: [
      SelectionDataType.CODE_LIKE,
      SelectionDataType.ERROR_LIKE,
      SelectionDataType.TERMINAL_LIKE,
    ],
    pageCategories: [
      PageCategory.DEV_DOCS,
      PageCategory.CODE_REPO,
      PageCategory.BLOG,
      PageCategory.FORUM,
      PageCategory.DOCUMENTATION,
      PageCategory.WIKI,
      PageCategory.PRODUCTIVITY,
      PageCategory.EDUCATION,
      PageCategory.TEXTBOOKS,
    ],
    systemPrompt:
      "You are a code review assistant. Analyze the provided code or error message for potential bugs, inefficiencies, security vulnerabilities, and style issues. Provide specific suggestions for improvements with brief explanations. Include examples of fixed code where helpful. \n\n**IMPORTANT:** Present feedback using Markdown. Use headings (`## Suggestions`), bullet points (`* **Suggestion:**...\n  * **Reasoning:**...`), inline code (`function()`), and code blocks (```language\nsuggested code\n```).",
    userPrompt:
      "Review this code for potential bugs and improvements: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    icon: PiBug,
  },
  {
    id: "refactor_code",
    name: "Refactor",
    description: "Improve code structure/readability",
    contextTypes: [
      SelectionContextType.CODE_BLOCK,
      SelectionContextType.GENERAL,
    ],
    dataTypes: [SelectionDataType.CODE_LIKE],
    pageCategories: [
      PageCategory.DEV_DOCS,
      PageCategory.CODE_REPO,
      PageCategory.BLOG,
      PageCategory.FORUM,
      PageCategory.DOCUMENTATION,
      PageCategory.WIKI,
      PageCategory.PRODUCTIVITY,
      PageCategory.EDUCATION,
      PageCategory.TEXTBOOKS,
    ],
    systemPrompt:
      "You are a code refactoring expert. Rewrite the provided code to improve its structure, readability, and maintainability while preserving its functionality. Focus on applying simple best practices, improving naming, or simplifying logic. Avoid major architectural changes. \n\n**IMPORTANT:** Format the refactored code using Markdown code blocks (```language\nrefactored code\n```). Add explanatory notes using bullet points (`*`) if necessary.",
    userPrompt: "Refactor this code (focus on readability): {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    icon: PiArrowClockwise,
  },
  {
    id: "add_comments",
    name: "Add comments",
    description: "Add helpful comments to code",
    contextTypes: [
      SelectionContextType.CODE_BLOCK,
      SelectionContextType.GENERAL,
    ],
    dataTypes: [SelectionDataType.CODE_LIKE],
    pageCategories: [
      PageCategory.DEV_DOCS,
      PageCategory.CODE_REPO,
      PageCategory.BLOG,
      PageCategory.FORUM,
      PageCategory.DOCUMENTATION,
      PageCategory.WIKI,
      PageCategory.PRODUCTIVITY,
      PageCategory.EDUCATION,
      PageCategory.TEXTBOOKS,
    ],
    systemPrompt:
      "You are a code documentation specialist. Add clear, helpful comments to the provided code explaining its purpose, functionality, and any complex parts. Focus on 'why' rather than 'what'. Follow language conventions. \n\n**IMPORTANT:** Provide the code with comments added, using Markdown code blocks (```language\ncode with comments\n```).",
    userPrompt: "Add comments to this code: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    icon: PiChatCenteredText,
  },
  {
    id: "explain_technical_error",
    name: "Explain",
    description: "Explain a technical error",
    contextTypes: [SelectionContextType.CODE_BLOCK],
    dataTypes: [SelectionDataType.ERROR_LIKE],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a helpful debugging assistant. The user has selected text that appears to be a technical error message. Explain what this error likely means in simple terms. Suggest potential common causes or general troubleshooting steps relevant to this type of error. Do NOT invent specific solutions without more context. \n\n**IMPORTANT:** Format the explanation using Markdown. Use headings (`## Error Explanation`, `## Possible Causes`) and bullet points (`*`). Use inline code (`code`) for technical terms.",
    userPrompt: "Explain this error message: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    icon: PiWarningCircle,
  },
  {
    id: "prioritize_list",
    name: "Prioritize",
    description: "Order list items by importance",
    contextTypes: [SelectionContextType.LIST],
    dataTypes: ANY_DATA,
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a prioritization assistant. Analyze the items in the provided list and reorganize them based on likely importance or urgency. If context is unclear, state your assumption or offer one prioritization scheme. Briefly explain the reasoning for the top items. \n\n**IMPORTANT:** Present the prioritized list using Markdown numbered lists (`1.`). Add brief reasoning in italics (*Reason:...*).",
    userPrompt: "Prioritize this list: {{selection}}",
    llmParams: PARAMETER_PRESETS.BALANCED,
    icon: PiTrophy,
  },
  {
    id: "format_as_list",
    name: "Format as List",
    description: "Convert text block into a list",
    contextTypes: [SelectionContextType.GENERAL],
    dataTypes: [
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.MARKDOWN,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a formatting assistant. The user selected a block of text. Identify distinct items or points within the text and format them as a Markdown bulleted list (`*`) or numbered list (`1.`) if order seems important. \n\n**IMPORTANT:** Output only the formatted list.",
    userPrompt: "Format this text as a list: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    icon: PiListPlus,
  },
  {
    id: "format_as_table",
    name: "Format as Table",
    description: "Convert text block into a Markdown table",
    contextTypes: [
      SelectionContextType.GENERAL,
      SelectionContextType.LIST,
      SelectionContextType.TABLE,
    ],
    dataTypes: [
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.MARKDOWN,
      SelectionDataType.NUMERIC,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: ALL_PAGE_CATEGORIES,
    systemPrompt:
      "You are a formatting assistant. The user selected text that might represent tabular data (or a list suitable for a table). Attempt to structure this data into a Markdown table with appropriate headers. Infer headers if not explicitly present. \n\n**IMPORTANT:** Output only the Markdown table. Ensure correct Markdown table syntax.",
    userPrompt: "Format this text as a Markdown table: {{selection}}",
    llmParams: PARAMETER_PRESETS.PRECISE,
    icon: PiTable,
  },
  {
    id: "analyze_claim",
    name: "Analyze",
    description: "Evaluate claim's logic/bias (no external check)",
    contextTypes: [SelectionContextType.GENERAL, SelectionContextType.QUOTE],
    dataTypes: [
      SelectionDataType.SENTENCE,
      SelectionDataType.PARAGRAPH,
      SelectionDataType.SOCIAL_MEDIA,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: [
      PageCategory.NEWS,
      PageCategory.BLOG,
      PageCategory.SOCIAL,
      PageCategory.FORUM,
      PageCategory.POLITICAL,
      PageCategory.WIKI,
      PageCategory.MAGAZINES,
      PageCategory.NEWSPAPERS,
      PageCategory.JOURNALS,
    ],
    systemPrompt:
      "You are a critical thinking assistant. Analyze the selected claim based *only* on the provided text and general knowledge. Identify the main assertion. Explain potential logical fallacies, biases, assumptions, or missing context within the text itself. **Crucially, state clearly that you cannot verify external facts.** Explain what *kind* of external evidence would be needed to evaluate the claim's truthfulness. \n\n**IMPORTANT:** Format your response using Markdown. Use headings like `## Claim Analysis`, `## Potential Issues`, `## Verification Needs`. Do NOT state if the claim is true or false.",
    userPrompt: "Analyze this claim (focus on logic/bias): {{selection}}",
    llmParams: PARAMETER_PRESETS.FACTUAL,
    icon: PiQuestion,
  },
  {
    id: "analyze_lyrics",
    name: "Analyze",
    description: "Interpret meaning and themes in lyrics",
    contextTypes: [
      SelectionContextType.GENERAL,
      SelectionContextType.LIST,
      SelectionContextType.QUOTE,
    ],
    dataTypes: [
      SelectionDataType.POETRY,
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: [PageCategory.MUSIC],
    systemPrompt:
      "You are a literary analyst. Interpret the selected lyrics or poetry. Identify themes, metaphors, imagery, and potential meanings. Consider context if apparent. Discuss possible intentions and emotional impact. \n\n**IMPORTANT:** Format the analysis using Markdown. Use headings (`## Themes`, `## Interpretation`) and bullet points (`*`).",
    userPrompt: "Analyze these lyrics/poem: {{selection}}",
    llmParams: PARAMETER_PRESETS.CREATIVE,
    icon: PiMusicNoteSimple,
  },
  {
    id: "plan_itinerary",
    name: "Itinerary",
    description: "Suggest travel activities based on description",
    contextTypes: [SelectionContextType.GENERAL, SelectionContextType.LIST],
    dataTypes: [
      SelectionDataType.PARAGRAPH,
      SelectionDataType.LONG_TEXT,
      SelectionDataType.MARKDOWN,
      SelectionDataType.PLAIN_TEXT,
    ],
    pageCategories: [PageCategory.TRAVEL],
    systemPrompt:
      "You are a travel planning assistant. Based on the selected location description or travel blog text, suggest a potential 1-day itinerary of activities, sights, or experiences. Consider different interests and a logical flow if possible from the text. \n\n**IMPORTANT:** Format the itinerary using Markdown. Use a numbered list (`1.`) for activities and bold (`**activity**`).",
    userPrompt: "Suggest an itinerary based on this text: {{selection}}",
    llmParams: PARAMETER_PRESETS.CREATIVE,
    icon: PiSuitcaseSimple,
  },
];
